# Generated by Django 5.1.2 on 2024-10-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paystack_reference',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
